---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: amazon/aws-cli

params:
  AWS_ACCESS_KEY_ID: ((((aws-credentials)).access_key))
  AWS_SECRET_ACCESS_KEY: ((((aws-credentials)).secret_key))
  AWS_SESSION_TOKEN: ((((aws-credentials)).security_token))

inputs:
- name: source

run:
  path: aws
  args:
  - s3
  - sync
  - source
  - ((target))
