---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: amazon/aws-cli

params:
  AWS_ACCESS_KEY_ID: (( concat "((aws/sts/" aws.credentials ".access_key))" ))
  AWS_SECRET_ACCESS_KEY: (( concat "((aws/sts/" aws.credentials ".secret_key))" ))
  AWS_SESSION_TOKEN: (( concat "((aws/sts/" aws.credentials ".security_token))" ))

inputs:
- name: source

run:
  path: aws
  args:
  - s3
  - sync
  - source
  - (( grab aws.target ))
