---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: openpolicyagent/opa
    tag: latest


inputs:
- name: source

outputs:
- name: bundle

run:
  path: /opa
  dir: source
  args:
  - build
  - .
  - --bundle
  - --output
  - ../bundle/bundle.tar.gz
