---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: openpolicyagent/opa
    tag: latest

inputs:
- name: source

run:
  path: /opa
  dir: source
  args:
  - fmt
  - .
  - --fail
  - --list
