---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/python-build" ))
    inject: (( inject registry.private.source ))

inputs:
- name: source

outputs:
- name: package

caches:
- path: pip-cache

run:
  path: bash
  args:
  - -e
  - -o
  - pipefail
  - -x
  - -c
  - >-
      (( concat "mkdir workdir && cp -R source/" python.pathspec " workdir/ &&
      cd source &&
      poetry export --format requirements.txt --without-hashes |
      python3 -m pip install
      --cache-dir ../pip-cache
      --upgrade
      --target ../workdir/
      --isolated
      --retries 1
      --timeout 1
      --requirement /dev/stdin &&
      cd ../workdir &&
      zip -v -9 -r ../package/package.zip ." ))
