---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/python-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

inputs:
- name: source
- name: virtual-environment
  path: source/.venv
- name: concourse-pipeline-library

outputs:
- name: flake8

run:
  path: bash
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      ./concourse-pipeline-library/scripts/stablepath && cd source &&
      poetry run flake8 --format json --output-file ../flake8/output.json
      ((python-pathspec))
