---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/python-build" ))
    inject: (( inject registry.private.source ))

params:
  PYTHONPATH: ../__pypackages__

inputs:
- name: source
- name: __pypackages__

outputs:
- name: flake8

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -x
  - -c
  - >-
      (( concat
      "python -m flake8 --format json --output-file ../flake8/output.json "
      python.pathspec
      ))
