---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/python-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

params:
  PYTHONPATH: ./__pypackages__

inputs:
- name: source
- name: pypackages
  path: source/__pypackages__

outputs:
- name: flake8

run:
  path: python
  dir: source
  args:
  - -m
  - flake8
  - --format
  - json
  - --output-file
  - ../flake8/output.json
  - ((python-pathspec))
