---
platform: linux

image_resource:

  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/python-build" ))
    inject: (( inject registry.private.source ))

inputs:

- name: source
  path: .

outputs:

- name: generated

run:

  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -c
  - tools/generate.sh
