---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/python-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

params:
  PYTHONPATH: ../__pypackages__

inputs:
- name: source
- name: __pypackages__

outputs:
- name: mypy

caches:
- path: mypy-cache

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      python -m mypy --cache-dir ../mypy-cache --strict --no-error-summary ((python-pathspec))
      | tee ../pylint/output.json
