---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/python-build" ))
    inject: (( inject registry.private.source ))

inputs:
- name: source

outputs:
- name: mypy

caches:
- path: mypy-cache

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      (( concat
      "poetry install && poetry run mypy --cache-dir ../mypy-cache --strict --no-error-summary
      --scripts-are-modules "
      python.pathspec
      " | tee ../mypy/output.txt"
      ))
