---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/python-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

inputs:
- name: source

outputs:
- name: mypy

caches:
- path: mypy-cache

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      poetry install && poetry run mypy --cache-dir ../mypy-cache --strict --no-error-summary
      --scripts-are-modules ((python-pathspec))
      | tee ../mypy/output.txt
