---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/python-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

inputs:
- name: source

outputs:
- name: pypackages
  path: source/__pypackages__

caches:
- path: source/__pypackages__
- path: pipcache

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      poetry export --format requirements.txt |
      python3 -m pip install
      --cache-dir ../pipcache
      --upgrade
      --target ./__pypackages__
      --isolated
      --retries 1
      --timeout 1
      --requirement /dev/stdin
