---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/python-build" ))
    inject: (( inject registry.private.source ))

inputs:
- name: source

outputs:
- name: __pypackages__

caches:
- path: __pypackages__
- path: pip-cache

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -x
  - -c
  - >-
      poetry export --format requirements.txt --dev --without-hashes |
      python3 -m pip install
      --cache-dir ../pip-cache
      --upgrade
      --target ../__pypackages__
      --isolated
      --retries 1
      --timeout 1
      --requirement /dev/stdin
