---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/python-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

inputs:
- name: source
- name: concourse-pipeline-library

outputs:
- name: virtual-environment
  path: source/.venv

caches:
- path: source/.venv

run:
  path: bash
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      ./concourse-pipeline-library/scripts/stablepath &&
      cd /tmp/stablepath/source &&
      poetry install --no-interaction
