---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/python-build" ))
    inject: (( inject registry.private.source ))

params:
  PYTHONPATH: ../__pypackages__

inputs:
- name: source
- name: __pypackages__

outputs:
- name: pylint

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      (( concat "python -m pylint --output-format=json " python.pathspec
      "| tee ../pylint/output.json" ))
