---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/python-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

params:
  PYTHONPATH: ./__pypackages__

inputs:
- name: source
- name: pypackages
  path: source/__pypackages__

outputs:
- name: pylint

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      python -m pylint --output-format=json ((python-pathspec))
      | tee ../pylint/output.json
