---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/python-build" ))
    inject: (( inject registry.private.source ))

inputs:
- name: source

outputs:
- name: yamllint

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -x
  - -c
  - yamllint --strict --format parsable . | tee ../yamllint/output.txt
