---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/python-build
    username: ((docker.robojackets.org/user.username))
    password: ((docker.robojackets.org/user.password))

inputs:
- name: source

outputs:
- name: yamllint

run:
  path: bash
  dir: source
  args:
  - -e
  - -o pipefail
  - -c
  - yamllint --format parsable . | tee ../yamllint/output.txt
