---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/python-build" ))
    inject: (( inject registry.private.source ))

params:
  AWS_ACCESS_KEY_ID: (( concat "((aws/sts/" aws.credentials ".access_key))" ))
  AWS_SECRET_ACCESS_KEY: (( concat "((aws/sts/" aws.credentials ".secret_key))" ))
  AWS_SESSION_TOKEN: (( concat "((aws/sts/" aws.credentials ".security_token))" ))

inputs:
- name: source

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -x
  - -c
  - >-
      poetry install --no-dev --no-ansi --no-interaction &&
      poetry run zappa update production --disable_progress
