---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/python-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

params:
  AWS_ACCESS_KEY_ID: ((((aws-credentials)).access_key))
  AWS_SECRET_ACCESS_KEY: ((((aws-credentials)).secret_key))
  AWS_SESSION_TOKEN: ((((aws-credentials)).security_token))

inputs:
- name: source

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      poetry install --no-dev --no-ansi --no-interaction &&
      poetry run zappa update ((stage)) --disable_progress
