---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/python-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

params:
  AWS_ACCESS_KEY_ID: ((((aws-credentials)).access_key))
  AWS_SECRET_ACCESS_KEY: ((((aws-credentials)).secret_key))
  AWS_SESSION_TOKEN: ((((aws-credentials)).security_token))
  PYTHONPATH: ../__pypackages__

inputs:
- name: source
- name: __pypackages__

run:
  path: python3
  dir: source
  args:
  - -m
  - zappa
  - update
  - ((stage))
