---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/fly
    username: ((docker.robojackets.org/user.username))
    password: ((docker.robojackets.org/user.password))

inputs:
- name: source

run:
  path: fly
  dir: source
  args:
  - validate-pipeline
  - --config
  - ((file))
