---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/fly-docker
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

inputs:
- name: source

run:
  path: fly
  dir: source
  args:
  - validate-pipeline
  - --config
  - ((file))
