---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: alpine/git

inputs:
- name: source

outputs:
- name: commit-sha

run:
  path: sh
  args:
  - -e
  - -x
  - -c
  - >-
      git -C source rev-parse HEAD > commit-sha/value
