---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task

params:
  CONTEXT: source
  IMAGE_ARG_base_image: ""
  BUILDKIT_PROGRESS: plain

inputs:
- name: source
- name: (( grab base_image.resource_name ))

outputs:
- name: image

run:
  path: build

caches:
- path: cache
