---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
- name: source
  path: .

outputs:
- name: image

run:
  path: build

caches:
- path: cache
