---
platform: linux

image_resource:

  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/fly" ))
    inject: (( inject registry.private.source ))

inputs:

- name: source
  path: .

- name: generated

run:

  path: tools/validate.sh
