---
resource_types:

- name: github-check
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/concourse-github-check-resource
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

- name: github-webhook
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/concourse-github-webhook-resource
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

- name: slack
  type: registry-image
  source:
    repository: mockersf/concourse-slack-notifier

resources:

- name: concourse-pipeline-library
  public: true
  type: git
  icon: github
  webhook_token: ((webhook-token))
  source:
    uri: https://github.com/RoboJackets/concourse-pipeline-library
    branch: main
    username: x-access-token
    password: ((github-com/token))

- name: pull-request
  public: true
  type: pull-request
  icon: source-pull
  webhook_token: ((webhook-token))
  source:
    repository: RoboJackets/concourse-pipeline-library
    access_token: ((github-com/token))
    base_branch: main

- name: yamllint-check
  public: true
  type: github-check
  icon: check-bold
  source:
    repository: concourse-pipeline-library
    pull_request: pull-request
    token: ((github-com/token))
    check_name: yamllint
    resource_name: yamllint-check
    annotations_format: yamllint

- name: validate-pipeline-check
  public: true
  type: github-check
  icon: check-bold
  source:
    repository: concourse-pipeline-library
    pull_request: pull-request
    token: ((github-com/token))
    check_name: validate-pipeline
    resource_name: validate-pipeline-check

- name: webhooks
  public: true
  type: github-webhook
  icon: webhook
  source:
    github_token: ((github-com/token))
    webhook_token: ((webhook-token))
    resources:
      concourse-pipeline-library:
        github_uri: https://github.com/RoboJackets/concourse-pipeline-library
        events:
        - push
      pull-request:
        github_uri: https://github.com/RoboJackets/concourse-pipeline-library
        events:
        - push
        - pull_request

- name: slack
  public: true
  type: slack
  icon: slack
  source:
    url: ((slack-webhook))

jobs:

- name: build-main
  public: true
  plan:

  - get: concourse-pipeline-library
    trigger: true

  - put: yamllint-check

  - task: yamllint
    file: concourse-pipeline-library/tasks/python/yamllint.yml
    input_mapping:
      source: concourse-pipeline-library
    on_failure:
      put: yamllint-check
      params:
        conclusion: failure
    on_abort:
      put: yamllint-check
      params:
        conclusion: cancelled
    on_error:
      put: yamllint-check
      params:
        conclusion: action_required

  - in_parallel:
    - put: yamllint-check
      params:
        conclusion: success
    - put: validate-pipeline-check

  - in_parallel:

    - task: validate-meta-pipeline
      file: concourse-pipeline-library/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: concourse-pipeline-library
      vars:
        pipeline: meta/pipeline.yml

    - task: validate-php-library-pipeline
      file: concourse-pipeline-library/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: concourse-pipeline-library
      vars:
        pipeline: pipelines/php/library.yml

    - task: validate-php-metapackage-pipeline
      file: concourse-pipeline-library/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: concourse-pipeline-library
      vars:
        pipeline: pipelines/php/metapackage.yml

    - task: validate-php-on-premises-pipeline
      file: concourse-pipeline-library/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: concourse-pipeline-library
      vars:
        pipeline: pipelines/php/on-premises.yml

    - task: validate-php-satis-pipeline
      file: concourse-pipeline-library/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: concourse-pipeline-library
      vars:
        pipeline: pipelines/php/satis.yml

    - task: validate-php-serverless-pipeline
      file: concourse-pipeline-library/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: concourse-pipeline-library
      vars:
        pipeline: pipelines/php/serverless.yml

    - task: validate-php-vapor-pipeline
      file: concourse-pipeline-library/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: concourse-pipeline-library
      vars:
        pipeline: pipelines/php/vapor.yml

    - task: validate-python-library-pipeline
      file: concourse-pipeline-library/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: concourse-pipeline-library
      vars:
        pipeline: pipelines/python/library.yml

    - task: validate-python-oci-build-pipeline
      file: concourse-pipeline-library/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: concourse-pipeline-library
      vars:
        pipeline: pipelines/python/oci-build.yml

    - task: validate-oci-build-pipeline
      file: concourse-pipeline-library/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: concourse-pipeline-library
      vars:
        pipeline: pipelines/oci-build.yml

    on_failure:
      put: validate-pipeline-check
      params:
        conclusion: failure
        title: Issues with pipelines
        summary: >-
          One or more pipelines failed `fly validate-pipeline`. Please review
          the output in Concourse for more information.
    on_abort:
      put: validate-pipeline-check
      params:
        conclusion: cancelled
    on_error:
      put: validate-pipeline-check
      params:
        conclusion: action_required

  - in_parallel:
    - put: validate-pipeline-check
      params:
        conclusion: success
        title: Pipelines look good
        summary: All pipelines passed `fly validate-pipeline`.

    - set_pipeline: pipeline-library
      file: concourse-pipeline-library/meta/pipeline.yml

    - set_pipeline: python-build
      file: concourse-pipeline-library/pipelines/oci-build.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/pipelines/python-build.yml

    - set_pipeline: php-build
      file: concourse-pipeline-library/pipelines/oci-build.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/pipelines/php-build.yml

    - set_pipeline: fly
      file: concourse-pipeline-library/pipelines/oci-build.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/pipelines/fly.yml

    - set_pipeline: github-approval
      file: concourse-pipeline-library/pipelines/python/oci-build.yml
      var_files:
      - concourse-pipeline-library/var_files/github/com.yml
      - concourse-pipeline-library/var_files/pipelines/github-approval.yml

    - set_pipeline: github-check
      file: concourse-pipeline-library/pipelines/python/oci-build.yml
      var_files:
      - concourse-pipeline-library/var_files/github/com.yml
      - concourse-pipeline-library/var_files/pipelines/github-check.yml

    - set_pipeline: github-deployment
      file: concourse-pipeline-library/pipelines/python/oci-build.yml
      var_files:
      - concourse-pipeline-library/var_files/github/com.yml
      - concourse-pipeline-library/var_files/pipelines/github-deployment.yml

    - set_pipeline: github-webhook
      file: concourse-pipeline-library/pipelines/python/oci-build.yml
      var_files:
      - concourse-pipeline-library/var_files/github/com.yml
      - concourse-pipeline-library/var_files/pipelines/github-webhook.yml

    - set_pipeline: gatech-aws-credentials
      file: concourse-pipeline-library/pipelines/python/library.yml
      var_files:
      - concourse-pipeline-library/var_files/github/com.yml
      - concourse-pipeline-library/var_files/pipelines/gatech-aws-credentials.yml

    - set_pipeline: aws-idp
      file: concourse-pipeline-library/pipelines/php/serverless.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/phpstan/defaults.yml
      - concourse-pipeline-library/var_files/codesniffer/defaults.yml
      - concourse-pipeline-library/var_files/pipelines/aws-idp.yml

    - set_pipeline: meraki-idp
      file: concourse-pipeline-library/pipelines/php/serverless.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/phpstan/defaults.yml
      - concourse-pipeline-library/var_files/codesniffer/defaults.yml
      - concourse-pipeline-library/var_files/pipelines/meraki-idp.yml

    - set_pipeline: apiary
      file: concourse-pipeline-library/pipelines/php/vapor.yml
      var_files:
      - concourse-pipeline-library/var_files/github/com.yml
      - concourse-pipeline-library/var_files/phpstan/custom.yml
      - concourse-pipeline-library/var_files/codesniffer/custom.yml
      - concourse-pipeline-library/var_files/pipelines/apiary.yml

    - set_pipeline: apiary-user
      file: concourse-pipeline-library/pipelines/php/library.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/phpstan/custom.yml
      - concourse-pipeline-library/var_files/codesniffer/defaults.yml
      - concourse-pipeline-library/var_files/pipelines/apiary-user.yml

    - set_pipeline: network-check
      file: concourse-pipeline-library/pipelines/php/library.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/phpstan/defaults.yml
      - concourse-pipeline-library/var_files/codesniffer/defaults.yml
      - concourse-pipeline-library/var_files/pipelines/network-check.yml

    - set_pipeline: error-pages
      file: concourse-pipeline-library/pipelines/php/library.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/phpstan/defaults.yml
      - concourse-pipeline-library/var_files/codesniffer/defaults.yml
      - concourse-pipeline-library/var_files/pipelines/error-pages.yml

    - set_pipeline: google-idp
      file: concourse-pipeline-library/pipelines/php/on-premises.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/phpstan/custom.yml
      - concourse-pipeline-library/var_files/codesniffer/defaults.yml
      - concourse-pipeline-library/var_files/pipelines/google-idp.yml

    - set_pipeline: jedi
      file: concourse-pipeline-library/pipelines/php/on-premises.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/phpstan/custom.yml
      - concourse-pipeline-library/var_files/codesniffer/defaults.yml
      - concourse-pipeline-library/var_files/pipelines/jedi.yml

    - set_pipeline: nextcloud-auth
      file: concourse-pipeline-library/pipelines/php/on-premises.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/phpstan/custom.yml
      - concourse-pipeline-library/var_files/codesniffer/defaults.yml
      - concourse-pipeline-library/var_files/pipelines/nextcloud-auth.yml

    - set_pipeline: mediawiki-auth
      file: concourse-pipeline-library/pipelines/php/on-premises.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/phpstan/custom.yml
      - concourse-pipeline-library/var_files/codesniffer/defaults.yml
      - concourse-pipeline-library/var_files/pipelines/mediawiki-auth.yml

    - set_pipeline: wordpress-auth
      file: concourse-pipeline-library/pipelines/php/on-premises.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/phpstan/custom.yml
      - concourse-pipeline-library/var_files/codesniffer/defaults.yml
      - concourse-pipeline-library/var_files/pipelines/wordpress-auth.yml

    - set_pipeline: satis
      file: concourse-pipeline-library/pipelines/php/satis.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/pipelines/satis.yml

    - set_pipeline: static-analysis
      file: concourse-pipeline-library/pipelines/php/metapackage.yml
      var_files:
      - concourse-pipeline-library/var_files/github/gatech.edu.yml
      - concourse-pipeline-library/var_files/pipelines/static-analysis.yml

  - put: webhooks
    inputs: []

  on_success:
    put: slack
    params:
      alert_type: success
      mode: normal
  on_failure:
    put: slack
    params:
      alert_type: failed
      mode: normal
  on_abort:
    put: slack
    params:
      alert_type: aborted
      mode: normal
  on_error:
    put: slack
    params:
      alert_type: failed
      mode: normal
      message: Task error, review logs

- name: build-pull-request
  public: true
  plan:

  - get: pull-request
    trigger: true
    version: every
    params:
      integration_tool: checkout

  - put: yamllint-check

  - task: yamllint
    file: pull-request/tasks/python/yamllint.yml
    input_mapping:
      source: pull-request
    on_failure:
      put: yamllint-check
      params:
        conclusion: failure
    on_abort:
      put: yamllint-check
      params:
        conclusion: cancelled
    on_error:
      put: yamllint-check
      params:
        conclusion: action_required

  - in_parallel:
    - put: yamllint-check
      params:
        conclusion: success
    - put: validate-pipeline-check

  - in_parallel:

    - task: validate-meta-pipeline
      file: pull-request/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: pull-request
      vars:
        pipeline: meta/pipeline.yml

    - task: validate-oci-build-pipeline
      file: pull-request/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: pull-request
      vars:
        pipeline: pipelines/oci-build.yml

    - task: validate-python-library-pipeline
      file: pull-request/tasks/fly-validate-pipeline.yml
      input_mapping:
        source: pull-request
      vars:
        pipeline: pipelines/python/library.yml

    on_success:
      put: validate-pipeline-check
      params:
        conclusion: success
        title: Pipelines look good
        summary: All pipelines passed `fly validate-pipeline`
    on_failure:
      put: validate-pipeline-check
      params:
        conclusion: failure
        title: Issues with pipelines
        summary: >-
          One or more pipelines failed `fly validate-pipeline`. Please review
          the output in Concourse for more information.
    on_abort:
      put: validate-pipeline-check
      params:
        conclusion: cancelled
    on_error:
      put: validate-pipeline-check
      params:
        conclusion: action_required
