---
resource_types:

- name: github-check
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/concourse-github-check-resource
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

- name: slack
  type: registry-image
  source:
    repository: mockersf/concourse-slack-notifier

resources:

- name: concourse-pipeline-library
  public: true
  type: git
  icon: github
  source:
    uri: https://github.com/RoboJackets/concourse-pipeline-library
    branch: main
    username: x-access-token
    password: ((github-com/token))

- name: ((source-repository))
  type: git
  public: true
  icon: github
  source:
    uri: https://((github-host))/RoboJackets/((source-repository))
    branch: ((base-branch))
    username: x-access-token
    password: ((((github-host-dashes))/token))
  webhook_token: ((webhook-token))

- name: pull-request
  public: true
  type: pull-request
  icon: source-pull
  webhook_token: ((webhook-token))
  source:
    repository: RoboJackets/((source-repository))
    access_token: ((((github-host-dashes))/token))
    v3_endpoint: ((github-rest-api-endpoint))
    v4_endpoint: ((github-graphql-api-endpoint))
    base_branch: ((base-branch))
    disable_forks: true

- name: poetry-install-check
  public: true
  type: github-check
  icon: check-bold
  source:
    repository: ((source-repository))
    pull_request: pull-request
    token: ((((github-host-dashes))/token))
    check_name: Poetry Install
    resource_name: poetry-install-check

- name: mypy-check
  public: true
  type: github-check
  icon: check-bold
  source:
    repository: ((source-repository))
    pull_request: pull-request
    token: ((((github-host-dashes))/token))
    check_name: mypy
    resource_name: mypy-check
    annotations_format: mypy

- name: flake8-check
  public: true
  type: github-check
  icon: check-bold
  source:
    repository: ((source-repository))
    pull_request: pull-request
    token: ((((github-host-dashes))/token))
    check_name: flake8
    resource_name: flake8-check
    annotations_format: flake8

- name: pylint-check
  public: true
  type: github-check
  icon: check-bold
  source:
    repository: ((source-repository))
    pull_request: pull-request
    token: ((((github-host-dashes))/token))
    check_name: pylint
    resource_name: pylint-check
    annotations_format: pylint

- name: build-check
  public: true
  type: github-check
  icon: check-bold
  source:
    repository: ((source-repository))
    pull_request: pull-request
    token: ((((github-host-dashes))/token))
    check_name: OCI Build
    resource_name: build-check

- name: push-check
  public: true
  type: github-check
  icon: check-bold
  source:
    repository: ((source-repository))
    pull_request: pull-request
    token: ((((github-host-dashes))/token))
    check_name: Push to Registry
    resource_name: push-check

- name: image
  type: registry-image
  public: true
  icon: docker
  source:
    repository: docker.robojackets.org/robojackets/((source-repository))
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

- name: pull-request-image
  type: registry-image
  public: true
  icon: docker
  source:
    repository: docker.robojackets.org/robojackets/((source-repository))
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))
    tag: pull-request

- name: slack
  public: true
  type: slack
  icon: slack
  source:
    url: ((slack-webhook))

jobs:

- name: build-((base-branch))
  public: true
  plan:

  - in_parallel:

    - get: concourse-pipeline-library

    - get: ((source-repository))
      trigger: true

  - put: poetry-install-check
    inputs:
    - ((source-repository))

  - task: poetry-install-dev
    file: concourse-pipeline-library/tasks/python/poetry-install-dev.yml
    input_mapping:
      source: ((source-repository))
    on_success:
      put: poetry-install-check
      params:
        conclusion: success
        title: Dependencies installed
        summary: Poetry successfully installed development dependencies.
      inputs:
      - poetry-install-check
      - ((source-repository))
    on_failure:
      put: poetry-install-check
      params:
        conclusion: failure
        title: Failed to install dependencies
        summary: Review the output within Concourse.
      inputs:
      - poetry-install-check
      - ((source-repository))
    on_abort:
      put: poetry-install-check
      params:
        conclusion: cancelled
      inputs:
      - poetry-install-check
      - ((source-repository))
    on_error:
      put: poetry-install-check
      params:
        conclusion: action_required
      inputs:
      - poetry-install-check
      - ((source-repository))

  - in_parallel:
    - do:
      - put: flake8-check
        inputs:
        - ((source-repository))
      - task: flake8
        file: concourse-pipeline-library/tasks/python/flake8.yml
        vars:
          python-pathspec: ((python-pathspec))
        input_mapping:
          source: ((source-repository))
        on_success:
          put: flake8-check
          params:
            conclusion: success
          inputs:
          - flake8
          - flake8-check
          - ((source-repository))
        on_failure:
          put: flake8-check
          params:
            conclusion: failure
          inputs:
          - flake8
          - flake8-check
          - ((source-repository))
        on_abort:
          put: flake8-check
          params:
            conclusion: cancelled
          inputs:
          - flake8
          - flake8-check
          - ((source-repository))
        on_error:
          put: flake8-check
          params:
            conclusion: action_required
          inputs:
          - flake8
          - flake8-check
          - ((source-repository))
    - do:
      - put: pylint-check
        inputs:
        - ((source-repository))
      - task: pylint
        file: concourse-pipeline-library/tasks/python/pylint.yml
        vars:
          python-pathspec: ((python-pathspec))
        input_mapping:
          source: ((source-repository))
        on_success:
          put: pylint-check
          params:
            conclusion: success
          inputs:
          - pylint
          - pylint-check
          - ((source-repository))
        on_failure:
          put: pylint-check
          params:
            conclusion: failure
          inputs:
          - pylint
          - pylint-check
          - ((source-repository))
        on_abort:
          put: pylint-check
          params:
            conclusion: cancelled
          inputs:
          - pylint
          - pylint-check
          - ((source-repository))
        on_error:
          put: pylint-check
          params:
            conclusion: action_required
          inputs:
          - pylint
          - pylint-check
          - ((source-repository))
    - do:
      - put: mypy-check
        inputs:
        - ((source-repository))
      - task: mypy
        file: concourse-pipeline-library/tasks/python/mypy.yml
        vars:
          python-pathspec: ((python-pathspec))
        input_mapping:
          source: ((source-repository))
        on_success:
          put: mypy-check
          params:
            conclusion: success
          inputs:
          - mypy
          - mypy-check
          - ((source-repository))
        on_failure:
          put: mypy-check
          params:
            conclusion: failure
          inputs:
          - mypy
          - mypy-check
          - ((source-repository))
        on_abort:
          put: mypy-check
          params:
            conclusion: cancelled
          inputs:
          - mypy
          - mypy-check
          - ((source-repository))
        on_error:
          put: mypy-check
          params:
            conclusion: action_required
          inputs:
          - mypy
          - mypy-check
          - ((source-repository))
    - do:
      - put: build-check
        inputs:
        - ((source-repository))

      - task: build
        file: concourse-pipeline-library/tasks/oci-build.yml
        input_mapping:
          source: ((source-repository))
        privileged: true
        timeout: 15m
        on_success:
          put: build-check
          params:
            conclusion: success
            title: Image built
            summary: The OCI image was built successfully.
          inputs:
          - build-check
          - ((source-repository))
        on_failure:
          put: build-check
          params:
            conclusion: failure
            title: Image failed to build
            summary: Review the output within Concourse.
          inputs:
          - build-check
          - ((source-repository))
        on_abort:
          put: build-check
          params:
            conclusion: cancelled
          inputs:
          - build-check
          - ((source-repository))
        on_error:
          put: build-check
          params:
            conclusion: action_required
          inputs:
          - build-check
          - ((source-repository))

  - put: push-check
    inputs:
    - ((source-repository))

  - put: image
    params:
      image: image/image.tar
    inputs: detect
    on_success:
      put: push-check
      params:
        conclusion: success
        title: Image pushed to registry
        summary: The image was successfully uploaded to the registry.
      inputs:
      - push-check
      - ((source-repository))
    on_failure:
      put: push-check
      params:
        conclusion: failure
        title: Image failed to push
        summary: Review the output within Concourse.
      inputs:
      - push-check
      - ((source-repository))
    on_abort:
      put: push-check
      params:
        conclusion: cancelled
      inputs:
      - push-check
      - ((source-repository))
    on_error:
      put: push-check
      params:
        conclusion: action_required
      inputs:
      - push-check
      - ((source-repository))


  on_success:
    put: slack
    params:
      alert_type: success
      mode: normal
    inputs: []
  on_failure:
    put: slack
    params:
      alert_type: failed
      mode: normal
    inputs: []
  on_abort:
    put: slack
    params:
      alert_type: aborted
      mode: normal
    inputs: []
  on_error:
    put: slack
    params:
      alert_type: failed
      mode: normal
      message: Task error, review logs
    inputs: []

- name: build-pull-request
  public: true
  plan:

  - in_parallel:

    - get: concourse-pipeline-library

    - get: pull-request
      trigger: true
      version: every
      params:
        integration_tool: checkout

  - put: poetry-install-check
    inputs:
    - pull-request

  - task: poetry-install-dev
    file: concourse-pipeline-library/tasks/python/poetry-install-dev.yml
    input_mapping:
      source: pull-request
    on_success:
      put: poetry-install-check
      params:
        conclusion: success
        title: Dependencies installed
        summary: Poetry successfully installed development dependencies.
      inputs:
      - poetry-install-check
      - pull-request
    on_failure:
      put: poetry-install-check
      params:
        conclusion: failure
        title: Failed to install dependencies
        summary: Review the output within Concourse.
      inputs:
      - poetry-install-check
      - pull-request
    on_abort:
      put: poetry-install-check
      params:
        conclusion: cancelled
      inputs:
      - poetry-install-check
      - pull-request
    on_error:
      put: poetry-install-check
      params:
        conclusion: action_required
      inputs:
      - poetry-install-check
      - pull-request

  - in_parallel:
    - do:
      - put: flake8-check
        inputs:
        - pull-request
      - task: flake8
        file: concourse-pipeline-library/tasks/python/flake8.yml
        vars:
          python-pathspec: ((python-pathspec))
        input_mapping:
          source: pull-request
        on_success:
          put: flake8-check
          params:
            conclusion: success
          inputs:
          - flake8
          - flake8-check
          - pull-request
        on_failure:
          put: flake8-check
          params:
            conclusion: failure
          inputs:
          - flake8
          - flake8-check
          - pull-request
        on_abort:
          put: flake8-check
          params:
            conclusion: cancelled
          inputs:
          - flake8
          - flake8-check
          - pull-request
        on_error:
          put: flake8-check
          params:
            conclusion: action_required
          inputs:
          - flake8
          - flake8-check
          - pull-request
    - do:
      - put: pylint-check
        inputs:
        - pull-request
      - task: pylint
        file: concourse-pipeline-library/tasks/python/pylint.yml
        vars:
          python-pathspec: ((python-pathspec))
        input_mapping:
          source: pull-request
        on_success:
          put: pylint-check
          params:
            conclusion: success
          inputs:
          - pylint
          - pylint-check
          - pull-request
        on_failure:
          put: pylint-check
          params:
            conclusion: failure
          inputs:
          - pylint
          - pylint-check
          - pull-request
        on_abort:
          put: pylint-check
          params:
            conclusion: cancelled
          inputs:
          - pylint
          - pylint-check
          - pull-request
        on_error:
          put: pylint-check
          params:
            conclusion: action_required
          inputs:
          - pylint
          - pylint-check
          - pull-request
    - do:
      - put: mypy-check
        inputs:
        - pull-request
      - task: mypy
        file: concourse-pipeline-library/tasks/python/mypy.yml
        vars:
          python-pathspec: ((python-pathspec))
        input_mapping:
          source: pull-request
        on_success:
          put: mypy-check
          params:
            conclusion: success
          inputs:
          - mypy
          - mypy-check
          - pull-request
        on_failure:
          put: mypy-check
          params:
            conclusion: failure
          inputs:
          - mypy
          - mypy-check
          - pull-request
        on_abort:
          put: mypy-check
          params:
            conclusion: cancelled
          inputs:
          - mypy
          - mypy-check
          - pull-request
        on_error:
          put: mypy-check
          params:
            conclusion: action_required
          inputs:
          - mypy
          - mypy-check
          - pull-request

    - do:
      - put: build-check

      - task: build
        file: concourse-pipeline-library/tasks/oci-build.yml
        input_mapping:
          source: pull-request
        privileged: true
        timeout: 15m
        on_success:
          put: build-check
          params:
            conclusion: success
            title: Image built successfully
            summary: The OCI image was built successfully.
          inputs:
          - pull-request
          - build-check
        on_failure:
          put: build-check
          params:
            conclusion: failure
            title: Image failed to build
            summary: Review the output within Concourse.
          inputs:
          - pull-request
          - build-check
        on_abort:
          put: build-check
          params:
            conclusion: cancelled
          inputs:
          - pull-request
          - build-check
        on_error:
          put: build-check
          params:
            conclusion: action_required
          inputs:
          - pull-request
          - build-check

  - put: push-check
    inputs:
    - pull-request

  - put: pull-request-image
    params:
      image: image/image.tar
      additional_tags: pull-request/.git/resource/author
    inputs: detect
    on_success:
      put: push-check
      params:
        conclusion: success
        title: Image pushed to registry
        summary: The image was successfully uploaded to the registry.
      inputs:
      - push-check
      - pull-request
    on_failure:
      put: push-check
      params:
        conclusion: failure
        title: Image failed to push
        summary: Review the output within Concourse.
      inputs:
      - push-check
      - pull-request
    on_abort:
      put: push-check
      params:
        conclusion: cancelled
      inputs:
      - push-check
      - pull-request
    on_error:
      put: push-check
      params:
        conclusion: action_required
      inputs:
      - push-check
      - pull-request
