---
template: php/laravel

repository:
  name: apiary
  github: github.com
  main_branch: master

deployment:
  automatic_deployment_environment: test
  environment_urls:
    test: https://apiary-test.robojackets.org
    production: https://my.robojackets.org

php:
  codesniffer_config: phpcs.xml
  phpstan_config: phpstan.neon

resource_types:
- name: github-webhook
  defaults:
    resources:
      apiary: (( grab webhook_configuration ))

resources:

- name: tests-check
  public: true
  type: github-check
  icon: check
  source:
    check_name: Tests
    resource_name: tests-check

tasks:

  run_tests:

    do:
    - put: tests-check
      inputs: []
    - task: test
      config: (( load "tasks/php/composer-run-test.yml" ))
      input_mapping:
        source: (( grab repository.name ))
      on_success:
        put: tests-check
        params:
          conclusion: success
          title: All tests passed
          summary: All tests passed
        inputs:
        - tests-check
      on_failure:
        inject: (( inject tasks.run_tests.do.1.on_success ))
        params:
          conclusion: failure
          title: Some tests failed
          summary: Review the output within Concourse.
      on_abort:
        inject: (( inject tasks.run_tests.do.1.on_success ))
        params:
          conclusion: cancelled
      on_error:
        inject: (( inject tasks.run_tests.do.1.on_success ))
        params:
          conclusion: action_required
      timeout: 5m

jobs:

- name: (( concat "build-" repository.main_branch ))
  plan:

  - (( insert after 1 ))

  - (( grab tasks.run_tests ))

- name: build-pull-request
  plan:

  - (( insert after 1 ))

  - inject: (( inject tasks.run_tests ))
    do:

    - (( inline ))

    - {}

    - input_mapping:
        source: pull-request
