---
template: oci-build

repository:

  name: fly
  github: github.gatech.edu
  main_branch: main

base_image:

  repository: alpine
  tag: latest
  icon: image-filter-hdr

resource_types:

- name: github-webhook
  defaults:
    resources:
      fly: (( grab webhook_configuration ))

resources:

- name: concourse
  type: github-release
  public: true
  icon: concourse-ci
  source:
    owner: concourse
    repository: concourse
    access_token: (("github.com"/token.token))
  check_every: 1h

jobs:

- name: (( concat "build-" repository.main_branch ))
  plan:

  - in_parallel:

    - (( append ))

    - get: concourse
      trigger: true
      params:
        globs:
        - fly-*-linux-amd64.tgz

  - {}

  - task: (( inject tasks.build_image))
    config:
      inject: (( defer inject build_task ))
      inputs:
      - name: concourse
        path: source/concourse

- name: build-pull-request
  plan:

  - in_parallel:

    - (( append ))

    - get: concourse
      params:
        globs:
        - fly-*-linux-amd64.tgz

build_task: (( load "tasks/oci-build.yml" ))
