---
template: python/oci-build

repository:
  name: concourse-github-deployment-resource
  github: github.com
  main_branch: main

base_image:
  repository: python
  tag: 3.8-alpine
  icon: language-python

python:
  pathspec: src/*

resource_types:
- name: github-webhook
  defaults:
    resources:
      concourse-github-deployment-resource: (( grab webhook_configuration ))
