---
template: php/library

repository:
  name: meilisearch-index-settings-helper
  github: github.gatech.edu
  main_branch: main

php:
  codesniffer_config: vendor/robojackets/static-analysis/defaults/phpcs.xml
  phpstan_config: vendor/robojackets/static-analysis/defaults/phpstan.neon

resource_types:
- name: github-webhook
  defaults:
    resources:
      meilisearch-index-settings-helper: (( grab webhook_configuration ))
