---
resource_types:

- (( append ))

- name: github-approval
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/concourse-github-approval-resource" ))
    inject: (( inject registry.private.source ))
  defaults:
    pull_request_url: ((.:pull_request_url))
    commit: ((.:commit))
    token: (( concat "((\"" repository.github "\"/token.token))" ))
  tags:
  - resources

- name: github-merge
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/concourse-github-merge-resource" ))
    inject: (( inject registry.private.source ))
  defaults:
    pull_request_url: ((.:pull_request_url))
    commit: ((.:commit))
    token: (( concat "((\"" repository.github "\"/token.token))" ))
  tags:
  - resources

resources:

- (( append ))

- name: approve-pull-request
  public: true
  type: github-approval
  icon: check-circle
  tags:
  - resources

- name: merge-pull-request
  public: true
  type: github-merge
  icon: source-merge
  tags:
  - resources

jobs:

- name: build-pull-request
  plan:

  - (( append ))

  - put: approve-pull-request
    inputs: []

  - put: merge-pull-request
    inputs: []
