---
deployment:
  environment_urls: (( param "Where is this code deployed?" ))

resource_types:

- (( append ))

- name: github-deployment
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/concourse-github-deployment-resource" ))
    inject: (( inject registry.private.source ))
  defaults:
    repository_url: (( concat "(( grab resources." repository.name ".source.uri ))" ))
    commit: ((.:commit))
    token: (( concat "((\"" repository.github "\"/token.token))" ))
    resource_name: deployment
    environment_urls: (( grab deployment.environment_urls ))
  tags:
  - resources

resources:

- (( append ))

- name: deployment
  public: true
  type: github-deployment
  icon: ferry
  tags:
  - resources
