---
resource_types:

- name: github-check
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/concourse-github-check-resource
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

- name: github-webhook
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/concourse-github-webhook-resource
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

- name: slack
  type: registry-image
  source:
    repository: mockersf/concourse-slack-notifier

resources:

- name: concourse-pipeline-library
  public: true
  type: git
  icon: github
  source:
    uri: https://github.com/RoboJackets/concourse-pipeline-library
    branch: main
    username: x-access-token
    password: ((github-com/token))

- name: ((source-repository))
  type: git
  public: true
  icon: github
  source:
    uri: https://((github-host))/RoboJackets/((source-repository))
    branch: ((base-branch))
    username: x-access-token
    password: ((((github-host-dashes))/token))
  webhook_token: ((webhook-token))

- name: pull-request
  public: true
  type: pull-request
  icon: source-pull
  webhook_token: ((webhook-token))
  source:
    repository: RoboJackets/((source-repository))
    access_token: ((((github-host-dashes))/token))
    v3_endpoint: ((github-rest-api-endpoint))
    v4_endpoint: ((github-graphql-api-endpoint))
    base_branch: ((base-branch))
    disable_forks: true

- name: composer-install-check
  public: true
  type: github-check
  icon: check-bold
  source:
    repository: ((source-repository))
    pull_request: pull-request
    token: ((((github-host-dashes))/token))
    check_name: Composer Install
    resource_name: composer-install-check

- name: webhooks
  public: true
  type: github-webhook
  icon: webhook
  source:
    github_token: ((((github-host-dashes))/token))
    webhook_token: ((webhook-token))
    resources:
      ((source-repository)):
        github_uri: https://((github-host))/RoboJackets/((source-repository))
        events:
        - push
      pull-request:
        github_uri: https://((github-host))/RoboJackets/((source-repository))
        events:
        - push
        - pull_request

- name: slack
  public: true
  type: slack
  icon: slack
  source:
    url: ((slack-webhook))

jobs:

- name: build-((base-branch))
  public: true
  plan:

  - in_parallel:

    - get: concourse-pipeline-library

    - get: ((source-repository))
      trigger: true

  - put: composer-install-check
    inputs:
    - ((source-repository))

  - task: composer-install-dev
    file: concourse-pipeline-library/tasks/php/composer-install-dev.yml
    input_mapping:
      source: ((source-repository))
    on_success:
      put: composer-install-check
      params:
        conclusion: success
        title: Dependencies installed
        summary: Composer successfully installed development dependencies.
      inputs:
      - composer-install-check
      - ((source-repository))
    on_failure:
      put: composer-install-check
      params:
        conclusion: failure
        title: Failed to install dependencies
        summary: Review the output within Concourse.
      inputs:
      - composer-install-check
      - ((source-repository))
    on_abort:
      put: composer-install-check
      params:
        conclusion: cancelled
      inputs:
      - composer-install-check
      - ((source-repository))
    on_error:
      put: composer-install-check
      params:
        conclusion: action_required
      inputs:
      - composer-install-check
      - ((source-repository))

  - put: webhooks
    inputs: []

  on_success:
    put: slack
    params:
      alert_type: success
      mode: normal
    inputs: []
  on_failure:
    put: slack
    params:
      alert_type: failed
      mode: normal
    inputs: []
  on_abort:
    put: slack
    params:
      alert_type: aborted
      mode: normal
    inputs: []
  on_error:
    put: slack
    params:
      alert_type: failed
      mode: normal
      message: Task error, review logs
    inputs: []

- name: build-pull-request
  public: true
  plan:

  - in_parallel:

    - get: concourse-pipeline-library

    - get: pull-request
      trigger: true
      version: every
      params:
        integration_tool: checkout

  - put: composer-install-check
    inputs:
    - pull-request

  - task: composer-install-dev
    file: concourse-pipeline-library/tasks/php/composer-install-dev.yml
    input_mapping:
      source: pull-request
    on_success:
      put: composer-install-check
      params:
        conclusion: success
        title: Dependencies installed
        summary: Composer successfully installed development dependencies.
      inputs:
      - composer-install-check
      - pull-request
    on_failure:
      put: composer-install-check
      params:
        conclusion: failure
        title: Failed to install dependencies
        summary: Review the output within Concourse.
      inputs:
      - composer-install-check
      - pull-request
    on_abort:
      put: composer-install-check
      params:
        conclusion: cancelled
      inputs:
      - composer-install-check
      - pull-request
    on_error:
      put: composer-install-check
      params:
        conclusion: action_required
      inputs:
      - composer-install-check
      - pull-request
