---
resource_types:

- (( append ))
- name: slack
  type: registry-image
  source:
    repository: mockersf/concourse-slack-notifier
  defaults:
    url: ((slack-webhook))

resources:

- (( append ))
- name: slack
  public: true
  type: slack
  icon: slack

jobs:

- name: (( concat "build-" repository.main_branch ))
  on_success:
    put: slack
    params:
      alert_type: success
      mode: normal
    inputs: []
  on_failure:
    inject: (( concat "(( inject jobs.build-" repository.main_branch ".on_success ))" ))
    params:
      alert_type: failed
  on_abort:
    inject: (( concat "(( inject jobs.build-" repository.main_branch ".on_success ))" ))
    params:
      alert_type: aborted
  on_error:
    inject: (( concat "(( inject jobs.build-" repository.main_branch ".on_success ))" ))
    params:
      alert_type: failed
      message: Task error, review logs
