---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/php-build" ))
    inject: (( inject registry.private.source ))

inputs:
- name: source

outputs:
- name: node_modules
  path: source/node_modules

run:
  path: npm
  dir: source
  args:
  - ci
  - --production
