---
disable_forks: false

merge:
- flavors/opa.yml

jobs:

- name: (( concat "build-" repository.main_branch ))
  public: true
  plan:

  - get: (( grab repository.name ))
    trigger: true

  - in_parallel:

    - (( grab tasks.fmt ))

    - (( grab tasks.test ))

    - (( grab tasks.build ))

  - task: upload
    config: (( load "tasks/aws/s3-sync.yml" ))
    input_mapping:
      source: bundle

- name: build-pull-request
  public: true
  plan:

  - get: pull-request
    trigger: true

  - in_parallel:

    - inject: (( inject tasks.fmt ))
      input_mapping:
        source: pull-request

    - inject: (( inject tasks.test ))
      input_mapping:
        source: pull-request

    - inject: (( inject tasks.build ))
      input_mapping:
        source: pull-request
