---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/php-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

inputs:
- name: concourse-pipeline-library
- name: source
- name: vendor
  path: source/vendor

outputs:
- name: codesniffer

run:
  path: vendor/bin/phpcs
  dir: source
  args:
  - --report=json
  - --report-file=../codesniffer/output.json
  - --standard=((codesniffer-config))
