---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/php-build" ))
    inject: (( inject registry.private.source ))

inputs:
- name: source
- name: vendor
  path: source/vendor
- name: public
  path: source/public

run:
  path: composer
  dir: source
  args:
  - run
  - test
