---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/php-build" ))
    inject: (( inject registry.private.source ))

params:
  COMPOSER_AUTH: ((composer-auth))

inputs:
- name: source

outputs:
- name: vendor
  path: source/vendor

caches:
- path: source/vendor

run:
  path: composer
  dir: source
  args:
  - install
  - --no-interaction
  - --no-progress
  - --optimize-autoloader
  - --classmap-authoritative
  - --no-dev
