---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/((build-image))
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

inputs:
- name: source
- name: vendor
  path: source/vendor

outputs:
- name: phan

run:
  path: vendor/bin/phan
  dir: source
  args:
  - --output-mode
  - json
  - --output
  - ../phan/output.json
  - --exclude-directory-list
  - vendor
  - --directory
  - .
  - --signature-compatibility
  - --redundant-condition-detection
  - --dead-code-detection
  - --strict-type-checking
  - --plugin
  - DollarDollarPlugin
  - --plugin
  - AlwaysReturnPlugin
  - --plugin
  - DuplicateArrayKeyPlugin
  - --plugin
  - PregRegexCheckerPlugin
  - --plugin
  - PrintfCheckerPlugin
  - --plugin
  - UnreachableCodePlugin
  - --plugin
  - NonBoolBranchPlugin
  - --plugin
  - NonBoolInLogicalArithPlugin
  - --plugin
  - DuplicateExpressionPlugin
  - --plugin
  - UnusedSuppressionPlugin
