---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/((build-image))
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

inputs:
- name: source
- name: vendor
  path: source/vendor

outputs:
- name: phan

run:
  path: vendor/bin/phan
  dir: source
  args:
  - --output-mode
  - json
  - --output
  - ../phan/output.json
