---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/php-build" ))
    inject: (( inject registry.private.source ))

inputs:
- name: source
- name: vendor
  path: source/vendor

outputs:
- name: phpstan

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      (( concat "php -f vendor/bin/phpstan analyse --level=max
      --configuration=" php.phpstan_config " --error-format=json .
      | tee ../phpstan/output.json" ))
