---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/php-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

inputs:
- name: source
- name: vendor
  path: source/vendor

outputs:
- name: phpstan

# Have to run composer install here again because the phpstan extension
# installer uses absolute paths
run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      composer install --no-interaction --no-progress
      --optimize-autoloader --classmap-authoritative &&
      php -f vendor/bin/phpstan analyse --level=max
      --configuration=((phpstan-config)) --error-format=json .
      | tee ../phpstan/output.json
