---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/((build-image))
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

inputs:
- name: source
- name: vendor
  path: source/vendor

outputs:
- name: phpstan

run:
  path: bash
  dir: source
  args:
  - -e
  - -o
  - pipefail
  - -c
  - >-
      php -f vendor/bin/phpstan analyse --level=max
      --configuration=((phpstan-config)) --error-format=json .
      | tee ../phpstan/output.json
