---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/php-build" ))
    inject: (( inject registry.private.source ))

inputs:
- name: source

outputs:
- name: source

run:
  path: php
  dir: source
  args: []
