---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/php-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

inputs:
- name: source

outputs:
- name: source

run:
  path: php
  dir: source
  args:
  - -f
  - ((filename))
