---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: (( join "/" registry.private.hostname "robojackets/php-build" ))
    inject: (( inject registry.private.source ))

params:
  COMPOSER_AUTH:
    http-basic:
      ((github-host)):
        username: x-access-token
        password: ((((github-host-dashes))/token.token))

inputs:
- name: source
- name: vendor
  path: source/vendor

outputs:
- name: build

run:
  path: php
  dir: source
  args:
  - -f
  - vendor/bin/satis
  - build
  - --no-interaction
