---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: docker.robojackets.org/robojackets/php-build
    username: ((docker-robojackets-org.username))
    password: ((docker-robojackets-org.password))

params:
  AWS_ACCESS_KEY_ID: ((((aws-credentials)).access_key))
  AWS_SECRET_ACCESS_KEY: ((((aws-credentials)).secret_key))
  AWS_SESSION_TOKEN: ((((aws-credentials)).security_token))
  SLS_DEBUG: 1

inputs:
- name: source
- name: vendor
  path: source/vendor
- name: node_modules
  path: source/node_modules

run:
  path: node_modules/.bin/serverless
  dir: source
  args:
  - deploy
  - --stage
  - ((stage))
